export const AJAX_CALL_BEGIN = 'AJAX_CALL_BEGIN';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS';

export const POST_TITLE_SUCCESS = 'POST_TITLE_SUCCESS';
export const VOTE_TITLE_SUCCESS = 'VOTE_TITLE_SUCCESS';
